# FROM mhart/alpine-node:0.10
FROM mhart/alpine-node:0.12
# FROM mhart/alpine-node:4
ENV NPM_VERSION=2

# FROM mhart/alpine-node:5
# ENV NPM_VERSION=3

RUN npm install -g npm@${NPM_VERSION} && \
  find /usr/lib/node_modules/npm -name test -o -name .bin -type d | xargs rm -rf && \
  rm -rf /usr/share/man /tmp/* /root/.npm /root/.node-gyp \
    /usr/lib/node_modules/npm/man /usr/lib/node_modules/npm/doc /usr/lib/node_modules/npm/html
